title: "Harrison Appiah"
author: "Harrison Appiah."
description:  "PhD Researcher | Material & Environmental Science" 
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:
  - {url: "/", title: "Home"}
  - {url: "/research/", title: "Research"}
  - {url: "/publications/", title: "Publications"}
  - {url: "/resume/", title: "Resume"}
  - {url: "/lab/", title: "Lab Gallery"}
  - { title: Blog, url: "/blog/" }
  
 

external:                       # accepts {file, title, url, icon, sidebaricon}
  - { title: Email, icon: envelope, url: "mailto:Appiah.harrison@yahoo.com" }
  - { title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=lj8Xn1sAAAAJ&hl=en" }
  - { title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/harrison-appiah-0a8a521a3/" }
comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed

